### ISSUE TITLE
Error  TypeError: expected str, bytes or os.PathLike object, not NoneType  when inport library : PySiddhi.core.SiddhiManager

### ISSUE THREAD

**Issue by nguyenvanson1998** [siddhi-io/PySiddhi#33]
Traceback (most recent call last):
  File "helloworld.py", line 3, in <module>
    from PySiddhi.core.SiddhiManager import SiddhiManager
  File "/home/thienchuaheadshot/.local/lib/python3.7/site-packages/PySiddhi/core/SiddhiManager.py", line 19, in <module>
    from PySiddhi.core.SiddhiAppRuntime import SiddhiAppRuntime
  File "/home/thienchuaheadshot/.local/lib/python3.7/site-packages/PySiddhi/core/SiddhiAppRuntime.py", line 18, in <module>
    from PySiddhi.core.debugger.SiddhiDebugger import SiddhiDebugger
  File "/home/thienchuaheadshot/.local/lib/python3.7/site-packages/PySiddhi/core/debugger/SiddhiDebugger.py", line 23, in <module>
    from PySiddhi.core.event.ComplexEvent import ComplexEvent
  File "/home/thienchuaheadshot/.local/lib/python3.7/site-packages/PySiddhi/core/event/ComplexEvent.py", line 23, in <module>
    class ComplexEvent(object):
  File "/home/thienchuaheadshot/.local/lib/python3.7/site-packages/PySiddhi/core/event/ComplexEvent.py", line 28, in ComplexEvent
    class Type(Enum):
  File "/home/thienchuaheadshot/.local/lib/python3.7/site-packages/PySiddhi/core/event/ComplexEvent.py", line 30, in Type
    "io.siddhi.pythonapi.proxy.core.event.complex_event.TypeProxy")().CURRENT(),
  File "/home/thienchuaheadshot/.local/lib/python3.7/site-packages/PySiddhi/SiddhiLoader.py", line 131, in _loadType
    loadLibrary()
  File "/home/thienchuaheadshot/.local/lib/python3.7/site-packages/PySiddhi/SiddhiLoader.py", line 97, in loadLibrary
    class_paths = ['.', os.path.join(siddhi_home, 'lib', '*')]
  File "/usr/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by vishnu9400** [comment]
export SIDDHISDK_HOME="{directory in which sdk was downloaded }/siddhi-sdk-5.1.0"

Run the above line of code before running your code. it works
